name: Patch Python

on: [ push ]

jobs:
  original:
    runs-on: [ hyokeun-ubuntu-18.04 ]
    strategy:
      matrix:
        python-version: ['3.11.0', '3.10.8', '3.10.7', '3.10.6', '3.10.5', '3.10.4', '3.10.3', '3.10.2', '3.10.1', '3.10.0', '3.9.15', '3.9.14', '3.9.13', '3.9.12', '3.9.11', '3.9.10', '3.9.9', '3.9.8', '3.9.7', '3.9.6', '3.9.5', '3.9.4', '3.9.3', '3.9.2', '3.9.1', '3.9.0', '3.8.14', '3.8.13', '3.8.12', '3.8.11', '3.8.10', '3.8.9', '3.8.8', '3.8.7', '3.8.6', '3.8.5', '3.8.4', '3.8.3', '3.8.2', '3.8.1', '3.8.0', '3.7.15', '3.7.14', '3.7.13', '3.7.12', '3.7.11', '3.7.10', '3.7.9', '3.7.8', '3.7.7', '3.7.6', '3.7.5', '3.7.1', '3.6.15', '3.6.14', '3.6.13', '3.6.12', '3.6.11', '3.6.10', '3.6.9', '3.6.8', '3.6.7', '3.5.10', '3.5.9', '3.5.4', '3.4.10', '3.3.7', '2.7.18', '2.7.17']
    steps:
      #- name: Check tools cache directory
      #  run: |
      #    echo "${{ runner.tool_cache }}"
      #    sudo rm -rf ~/.cache/pip/

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      #- name: Archive tool cache
      #  run: |
      #    set -x
      #    cd "${{ runner.tool_cache }}/Python"
      #    for x in `ls`; do
      #      if [[ -d $x ]]; then
      #        tar -zcf $x.tar.gz $x
      #      fi
      #    done

      #- name: Upload tool cache artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    path: ${{runner.tool_cache}}/tool_cache.tar.gz
