name: Patch Python

on: [ push ]

jobs:
  original:
    runs-on: [ hyokeun-test ]
    strategy:
      matrix:
        #python-version: [3.9.5, 3.9.4, 3.9.3, 3.9.2, 3.9.1, 3.9.0, 3.8.10, 3.8.9, 3.8.8, 3.8.7, 3.8.6, 3.8.5, 3.8.4, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.10, 3.7.9, 3.7.8, 3.7.7, 3.7.6, 3.7.5, 3.7.1, 3.6.13, 3.6.12, 3.6.11, 3.6.10, 3.6.9, 3.6.8, 3.6.7, 3.5.10, 3.5.9, 3.5.4, 3.4.10, 3.3.7, 2.7.18, 2.7.17]
        #python-version: [3.9.5, 3.8.4, 3.6.7]
        python-version: [3.8.4]
    steps:
      - name: Check tools cache directory
        run: |
          echo "${{ runner.tool_cache }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Archive tool cache
        run: |
          set -x
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      #- name: Upload tool cache artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    path: ${{runner.tool_cache}}/tool_cache.tar.gz
