name: Patch Python

on: [ push ]

jobs:
  original:
    runs-on: [ hyokeun-test ]
    strategy:
      matrix:
        #python-version: [3.8.4, 3.8.3]
        python-version: [3.8.4, 3.8.3, 3.8.2, 3.8.1, 3.8.0, 3.7.8, 3.7.7, 3.7.6, 3.7.5, 3.6.11, 3.6.10, 3.6.9, 3.6.8, 3.6.7, 3.5.9, 3.5.4, 3.4.10, 3.3.7, 2.7.18, 2.7.17]
    steps:
      - name: Check tools cache directory
        run: |
          echo "${{ runner.tool_cache }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
